[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  # Ensures .env loads during `netlify dev`
  env_files = ["./.env"]
  # Optional: if you want to explicitly set the dev port
  port = 8888

  [[redirects]]
    from = "/fn/*"
    to   = "/.netlify/functions/:splat"
    status = 200

[functions]
      external_node_modules = []
      included_files = ["netlify/lib/**"]